import java.io.IOException;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

    public static void main(String[] args) {

        // TODO add file extension as an option, i.e. -e "txt"

        if (args.length == 4){

            printInput(args);
            String pattern = args[1];
            String path = args[3];

            try {
                new FileWatcher(path, pattern);
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
        else {
            printHelp();
        }
    }

    private static void printHelp(){

        System.err.println("ERROR: Incorrect usage");
        System.out.println("Usage:");
        System.out.println("\tjava -jar logHecate.jar -p \"PATTERN_TO_MATCH\" -d \"path/to/file\"");

    }

    private static void printInput(String[] parameters){
        System.out.printf("Pattern to search for: '%s'\n", parameters[1]);
        System.out.printf("Watching directory: %s\n", parameters[3]);
    }
}
