import com.beust.jcommander.JCommander;
import com.beust.jcommander.ParameterException;

import java.io.IOException;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

    private final MainCLParameters mainArgs = new MainCLParameters();
    private final String appName = "logHecate";

    public static void main(String[] args) {

        // TODO add file extension as an option, i.e. -e "txt"

        App app = new App();
        app.handleInputArgs(args);
        app.run();
    }

    private void run() {
        System.out.printf("\nRunning %s with arguments:\n", appName);
        System.out.println(mainArgs);

        try {
            new FileWatcher(mainArgs.watchDir, mainArgs.pattern);
        } catch (IOException e) {
            System.err.printf("Error running: %s", e.getMessage());
        }
    }

    private void handleInputArgs(String[] args) {
        JCommander jCommander = new JCommander(mainArgs);
        jCommander.setProgramName(appName);

        try {
            jCommander.parse(args);
        }
        catch (ParameterException pe){
            System.err.println(pe.getMessage());
            showUsage(jCommander);
        }

        if (mainArgs.isHelp()){
            showUsage(jCommander);
        }
    }

    private void showUsage(JCommander jCommander) {
        jCommander.usage();
        System.exit(0);
    }
}
